Bash quote escaping

diff --git a/git-delete-gone-branches b/git-delete-gone-branches
--- a/git-delete-gone-branches
+++ b/git-delete-gone-branches
@@ -49,7 +49,7 @@ for branch in $(git for-each-ref --format '%(refname) %(upstream:track)' refs/he
 			git switch "$main_branch" &&
 			git branch -D "$branch"
 		else
-			echo "$app_name: [Error] Cannot delete main branch '$main_branch'." >&2
+			echo "$app_name: [Error] Cannot delete main branch ${main_branch@Q}." >&2
 		fi
 	else
 		git branch -D "$branch"
diff --git a/git-xlog b/git-xlog
--- a/git-xlog
+++ b/git-xlog
@@ -75,7 +75,7 @@ elif [[ ${diff_type@U} == 'A' || ${diff_type@U} == "ADDED" ]]; then
 elif [[ ${diff_type@U} == 'R' || ${diff_type@U} == "REMOVED" ]]; then
 	diff_mark='<'
 else
-	echo "$app_name: [Error] Unrecognized diff-type: '$diff_type'. Accepted values: 'A', 'Added', 'R', 'Removed'." >&2
+	echo "$app_name: [Error] Unrecognized diff-type: ${diff_type@Q}. Accepted values: 'A', 'Added', 'R', 'Removed'." >&2
 	exit 1
 fi
 
