Only check working tree when necessary

diff --git a/git-delete-gone-branches b/git-delete-gone-branches
--- a/git-delete-gone-branches
+++ b/git-delete-gone-branches
@@ -32,11 +32,6 @@ done
 
 git in-repo || exit $?
 
-if ! git is-worktree-clean; then
-	echo "$app_name: [Error] Cannot delete current branch: Working tree has changes." >&2
-	exit 1
-fi
-
 git fetch --all --prune &&
 
 current_branch="$(git rev-parse --abbrev-ref HEAD)" &&
@@ -45,6 +40,10 @@ main_branch="$(git main-branch --quiet)" &&
 for branch in $(git for-each-ref --format '%(refname) %(upstream:track)' refs/heads | awk '$2 == "[gone]" {sub("refs/heads/", "", $1); print $1}'); do
 	if [[ $branch == $current_branch ]]; then
 		if [[ $branch != $main_branch ]]; then
+			if ! git is-worktree-clean; then
+				echo "$app_name: [Error] Cannot delete current branch: Working tree has changes." >&2
+				exit 1
+			fi
 			git switch "$main_branch" &&
 			git branch -D "$branch"
 		else
