Improve error messages

diff --git a/git-delete-gone-branches b/git-delete-gone-branches
--- a/git-delete-gone-branches
+++ b/git-delete-gone-branches
@@ -20,11 +20,11 @@ while [[ $# -gt 0 ]]; do
 			exit 0
 			;;
 		-*)
-			echo "Unknown option: $1" >&2
+			echo "$app_name: [Error] Unknown option: $1" >&2
 			exit 1
 			;;
 		*)
-			echo "Unexpected argument: $1" >&2
+			echo "$app_name: [Error] Unexpected argument: $1" >&2
 			exit 1
 			;;
 	esac
@@ -33,7 +33,7 @@ done
 git in-repo || exit $?
 
 if ! git is-worktree-clean; then
-	echo "Error: Working tree has changes." >&2 &&
+	echo "$app_name: [Error] Cannot delete current branch: Working tree has changes." >&2
 	exit 1
 fi
 
@@ -48,7 +48,7 @@ for branch in $(git for-each-ref --format '%(refname) %(upstream:track)' refs/he
 			git switch "$main_branch" &&
 			git branch -D "$branch"
 		else
-			echo "Cannot delete main branch '$main_branch'." >&2
+			echo "$app_name: [Error] Cannot delete main branch '$main_branch'." >&2
 		fi
 	else
 		git branch -D "$branch"
diff --git a/git-is-branch-remote b/git-is-branch-remote
--- a/git-is-branch-remote
+++ b/git-is-branch-remote
@@ -27,7 +27,7 @@ for ((i = 1; i <= $#; i++)); do
 			break
 			;;
 		-*)
-			echo "Unknown option: $1" >&2
+			echo "$app_name: [Error] Unknown option: $1" >&2
 			exit 1
 			;;
 		*)
@@ -37,7 +37,7 @@ for ((i = 1; i <= $#; i++)); do
 done
 
 if [[ ${#args} -eq 0 ]]; then
-	echo "$app_name: No branch is given." >&2
+	echo "$app_name: [Error] No branch is given." >&2
 	echo "Try '$app_name -?' for more information." >&2
 	exit 2
 fi
diff --git a/git-legacy b/git-legacy
--- a/git-legacy
+++ b/git-legacy
@@ -25,7 +25,7 @@ while [[ $# -gt 0 ]]; do
 			exit 0
 			;;
 		-*)
-			echo "Unknown option: $1" >&2
+			echo "$app_name: [Error] Unknown option: $1" >&2
 			exit 1
 			;;
 		*)
@@ -58,12 +58,12 @@ if [[ $# -eq 0 ]]; then
 	rebase_loop
 elif [[ $# -eq 1 ]]; then
 	if ! git is-worktree-clean; then
-		echo "Error: Working tree has changes." >&2 &&
+		echo "$app_name: [Error] Working tree has changes." >&2 &&
 		return 1
 	fi
 	history_tip="$1"
 	git -c rebase.instructionFormat='%s%nexec git clean -fd; comm -13 -z <(git ls-tree --name-only -r %H -z | sort -z) <(git ls-files -z | sort -z) | xargs -0 rm -rf; git checkout --quiet %H -- . && git add . && GIT_AUTHOR_DATE="%ai" GIT_AUTHOR_NAME="%an" GIT_AUTHOR_EMAIL="%ae" GIT_COMMITTER_DATE="%ci" GIT_COMMITTER_NAME="%cn" GIT_COMMITTER_EMAIL="%ce" git commit --quiet --amend --no-edit' rebase -i --rebase-merges --update-refs "$history_tip"
 	rebase_loop
 else
-	echo "Invalid number of arguments ($#): Pass a git revision name to start rebase or nothing to continue automatic merge loop." >&2
+	echo "$app_name: [Error] Invalid number of arguments ($#): Pass a git revision name to start rebase or nothing to continue automatic merge loop." >&2
 fi
diff --git a/git-root b/git-root
--- a/git-root
+++ b/git-root
@@ -20,11 +20,11 @@ while [[ $# -gt 0 ]]; do
 			exit 0
 			;;
 		-*)
-			echo "Unknown option: $1" >&2
+			echo "$app_name: [Error] Unknown option: $1" >&2
 			exit 1
 			;;
 		*)
-			echo "Unexpected argument: $1" >&2
+			echo "$app_name: [Error] Unexpected argument: $1" >&2
 			exit 1
 			;;
 	esac
diff --git a/git-xlog b/git-xlog
--- a/git-xlog
+++ b/git-xlog
@@ -24,7 +24,7 @@ EOF
 
 getopt -q -T
 if [[ $? -ne 4 ]]; then
-    echo "$app_name: This script requires an enhanced getopt version." >&2
+    echo "$app_name: [Error] This script requires an enhanced getopt version." >&2
     exit 1
 fi
 
@@ -51,33 +51,29 @@ for ((i=0; i < ${#opts[@]}; i++)); do
         --)
             break
             ;;
-        *)
-            echo 'Internal error!' >&2
-            exit 1
-            ;;
     esac
 done
 
 if [[ ! -v diff_type ]]; then
-    echo "$app_name: Missing '--diff-type' argument." >&2
+    echo "$app_name: [Error] Missing '--diff-type' argument." >&2
     exit 1
 elif [[ -z $diff_type ]]; then
-    echo "$app_name: Missing value for argument '--diff-type'." >&2
+    echo "$app_name: [Error] Missing value for argument '--diff-type'." >&2
     exit 1
 elif [[ ${diff_type@U} == 'A' || ${diff_type@U} == "ADDED" ]]; then
     diff_mark='>'
 elif [[ ${diff_type@U} == 'R' || ${diff_type@U} == "REMOVED" ]]; then
     diff_mark='<'
 else
-    echo "$app_name: Unrecognized diff-type: '$diff_type'. Accepted values: 'A', 'Added', 'R', 'Removed'." >&2
+    echo "$app_name: [Error] Unrecognized diff-type: '$diff_type'. Accepted values: 'A', 'Added', 'R', 'Removed'." >&2
     exit 1
 fi
 
 if [[ ! -v log_opt ]]; then
-    echo "$app_name: Missing '--log-opt' argument." >&2
+    echo "$app_name: [Error] Missing '--log-opt' argument." >&2
     exit 1
 elif [[ -z $log_opt ]]; then
-    echo "$app_name: Missing value for argument '--log-opt'." >&2
+    echo "$app_name: [Error] Missing value for argument '--log-opt'." >&2
     exit 1
 fi
 
@@ -105,15 +101,15 @@ for ((i=0; i < ${#opts[@]}; i++)); do
 done
 
 if [[ ! -v search_text && ! -v search_regex ]]; then
-    echo "$app_name: No '-S' or '-G' found in log options." >&2
+    echo "$app_name: [Error] No '-S' or '-G' found in log options." >&2
     exit 1
 elif [[ -z $search_text && -z $search_regex ]]; then
-    echo "$app_name: Missing value for argument '-S' or '-G' in log options." >&2
+    echo "$app_name: [Error] Missing value for argument '-S' or '-G' in log options." >&2
     exit 1
 fi
 
 interrupt () {
-    echo "$app_name: Interrupted." >&2
+    echo "$app_name: [Error] Interrupted." >&2
     exit 1
 }
 
