Allow `git-forward` from a different remote

diff --git a/git-forward b/git-forward
--- a/git-forward
+++ b/git-forward
@@ -6,8 +6,9 @@ app_dir="$(dirname "${BASH_SOURCE[0]}")"
 print_help() {
 	expand -t 4 << EOF
 Usage:
-	$app_name
+	$app_name [REMOTE]
 		Fetch and fast forward all remote tracking branches.
+		If a remote is given, tries to update from remote branches with the same name.
 
 Options:
 	-?, --help
@@ -15,22 +16,36 @@ Options:
 EOF
 }
 
-while [[ $# -gt 0 ]]; do
-	case "$1" in
+args=()
+
+for ((i = 1; i <= $#; i++)); do
+	opt="${!i}"
+	case "$opt" in
 		-\?|--help)
 			print_help
 			exit 0
+			;;
+		--)
+			args+=("${@:i+1}")
+			break
 			;;
 		-*)
 			echo "$app_name: [Error] Unknown option: $1" >&2
 			exit 1
 			;;
 		*)
-			echo "$app_name: [Error] Unexpected argument: $1" >&2
-			exit 1
+			args+=("$opt")
 			;;
 	esac
 done
+
+if [[ ${#args[@]} -eq 1 ]]; then
+	remote="${args[0]}"
+elif [[ ${#args[@]} -gt 1 ]]; then
+	echo "$app_name: [Error] Too many arguments." >&2
+	echo "Try '$app_name -?' for more information." >&2
+	exit 2
+fi
 
 git rev-parse --git-dir > /dev/null || exit $?
 
@@ -44,15 +59,20 @@ trap interrupt INT
 git fetch --all &&
 current_branch="$(git rev-parse --abbrev-ref HEAD)" &&
 for branch in $(git branch --list --format="%(refname:short)"); do
-	upstream="$(git rev-parse --verify --quiet --abbrev-ref "$branch@{upstream}")"
-	has_upstream="$?"
+	if [[ -v remote ]]; then
+		upstream="$remote/$(git rev-parse --verify --quiet --abbrev-ref "$branch")"
+		has_upstream=0
+	else
+		upstream="$(git rev-parse --verify --quiet --abbrev-ref "$branch@{upstream}")"
+		has_upstream="$?"
+	fi
 	if [[ has_upstream -eq 0 ]]; then
 		branch_sha="$(git rev-parse --quiet --verify "$branch")" &&
 		upstream_sha="$(git rev-parse --quiet --verify "$upstream")" &&
 		if git merge-base --is-ancestor "$upstream_sha" "$branch_sha"; then
 			echo "'$branch' is already up to date with '${upstream%/$branch}'."
 			continue
-		fi
+		fi &&
 		if [[ "$branch" == "$current_branch" ]]; then
 			git pull --ff-only --quiet
 		else
